spring:
  application:
    name: eregister-gateway-service
  cloud:
    gateway:
    discovery:
      locator:
        enabled: true
server:
  port: 30000
eureka:
  client:
    serviceURL:
      defaultZone: http://eregister-discovery-service:8761/eureka
eregister:
  name: eregister
  http:
    port: 9998
  websocket:
    port: 9997
eregisterUserService:
  name: eregister-user-service
  port: 10000
#logging:
#  level:
#    reactor:
#      netty: INFO
#    org:
#      springframework:
#        cloud:
#          gateway: INFO