kind: Service
apiVersion: v1
metadata:
  name: eregister-gateway
  namespace: ingress-nginx
spec:
  selector:
    app: eregister-gateway
  ports:
  - name: http-port
    protocol: TCP
    targetPort: 30000
    port: 30000
    nodePort: 30000
  type: NodePort
